FROM nvidia/cuda:12.4.0-devel-ubuntu20.04


ARG DEBIAN_FRONTEND=noninteractive
ARG NPROC=4


WORKDIR /root


RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -y \
    wget unzip zip tar vim curl \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    libeigen3-dev \
    libvtk7-dev libgtk-3-dev libcanberra-gtk-module libcanberra-gtk3-module 

RUN apt-get update && apt-get install -y libatlas-base-dev gfortran \
    libparmetis-dev \
    libtbb-dev \
    software-properties-common \
    git \
    gdb \
    build-essential \
    cmake \
    python3-pip \
    libopencv-contrib-dev \
    libopencv-dev \
    libpcl-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
